version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/NetSdrClientApp" # Вказуємо папку першого проекту
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "nuget"
    directory: "/EchoTspServer" # Вказуємо папку другого проекту
    schedule:
      interval: "weekly"
